### ISSUE TITLE
How to import library with Gradle?

### ISSUE THREAD

**Issue by sebaslogen** [danfma/kodando#1]
Hi,
I was configuring a new KotlinJS project with Gradle and I want to give it a try to RxJS but I can't figure out how to import your library into the project.

I tried with this but it didn't work:
```
repositories {
    mavenCentral()
    maven { url "http://dl.bintray.com/danfma/maven" }
}

dependencies {
    compile "org.jetbrains.kotlin:kotlin-js-library:$kotlin_version"
    compile "io.kodando.kodando-rxjs:0.1.0-SNAPSHOT"
}
```

Is it even possible to use your library in a Gradle project?

Thanks for any help and for building the lib!

**Comment by danfma** [comment]
Sorry for being late, man! I didn't think that someone was trying to use this! 👏 

Actually, I need to update the published package on bintray (I deleted all the previous published packages when I transitioned to this new repository).

I will try to publish it as soon as I make it compile again with Kotlin 1.1. I will explain how to use in a README. I will update you soon.

**Comment by danfma** [comment]
While I'm trying to publish the package, give a look at this https://github.com/danfma/kodando/blob/master/samples/with-webpack/README.md

**Comment by danfma** [comment]
@sebaslogen try with this `compile "br.danfma:kodando-rxjs:0.1.0"`! I'm still learning how to publish on bintray.

**Comment by sebaslogen** [comment]
I tried in the gradle file and also manually searching for the pacjage in Bintray and it doesn't show up:
https://bintray.com/bintray/jcenter

Thanks for the help! I'm new to all the npm and webpack distribution systems, I'll give it a try on the weekend.

**Comment by danfma** [comment]
Ok, I'will check why is not working, in the mean time.

**Comment by danfma** [comment]
Hey, @sebaslogen. 

I don't know how to use gradle very well, but I think that you will have to use some plugin or task to unpack the dependencies' contents just like we do in Maven. I'm finishing some samples showing how to use these libraries. I will post probably tonight.

**Comment by danfma** [comment]
Give a look at this https://github.com/danfma/kodando-playground

**Comment by sebaslogen** [comment]
@danfma thanks for your help.
Adding the JS libraries manually is not a problem, the objective of importing with Gradle is making IntelliJ IDE aware of the library and recognize, auto-import and auto-complete objects with the library. I hope IntelliJ will add more documentation and examples of how to do this with Gradle.
Just as an example [here is the gradle file](https://github.com/sebaslogen/FibonacciCounter/blob/master/app/build.gradle) I was using to import a few kotlin-js libraries.

**Comment by danfma** [comment]
@sebaslogen hey man, I found what you can use:

```groovy
    build.doLast {
        configurations.compile.each { File file ->
            copy {
                includeEmptyDirs = false

                from zipTree(file.absoluteFile)
                into "lib/"
                include { fileTreeElement ->
                    def path = fileTreeElement.path

                    path.endsWith(".js") || path.endsWith(".js.map")
                }
            }
        }
    }
```

**Comment by danfma** [comment]
@sebaslogen https://github.com/danfma/kodando-react-sample.

**Comment by sebaslogen** [comment]
That dependency works perfectly from Gradle, I've checked the repo and I see several of your libraries there except the RxJS https://jcenter.bintray.com/br/danfma/

**Comment by danfma** [comment]
The Rx should work as well. I use it frequently, inclusive in one
implementation that mimics the Elm, but with Kotlin. I will post it too
later.
Em seg, 3 de abr de 2017 às 14:06, Sebas LG <notifications@github.com>
escreveu:

**Comment by danfma** [comment]
@sebaslogen Ohhh man, I saw it... That's because I didn't publish it to jCenter, but you can use the following URL https://dl.bintray.com/danfma/maven.

**Comment by sebaslogen** [comment]
Yes! I finally got it working in Gradle with: 
```
allprojects {
    repositories {
        jcenter()
        maven { url "https://dl.bintray.com/danfma/maven" }
    }
}
dependencies {
    compile "br.danfma:kodando-rxjs:5.0.0-v5"
}
```

Thanks @danfma !
