### ISSUE TITLE
Return type of Observable.throwError

### ISSUE THREAD

**Issue by motorro** [danfma/kodando#5]
Hi @danfma!

Great job you are doing!
I wanted to ask why did you decide to make `Observable.throwError` to have a signature of `IObservable<*>` rather than `IObservable<T>`?
This leads to inconvenience in  code like that:
```kotlin
val stream = Rx.Observable.of(listOf(1,2,3)).flatMap {
        if (it.isEmpty()) {
            // Warning suppress needed!
            @Suppress("UNCHECKED_CAST_TO_NATIVE_INTERFACE", "UNCHECKED_CAST")
            Rx.Observable.throwError(Error("Game has no levels defined")) as Rx.IObservable<String>
        } else {
            Rx.Observable.of(it.toString())
        }
}
```
Thing is Observable does not return an error object - it rather "throws" it through `onError` handler - so there should be no type conflict here.
RxJava [has it](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/Observable.java#L1664) with `<T>` there is no such problem.

**Comment by danfma** [comment]
To be honest with you, I don't remember why I had done that! But my Rx mappings are incomplete and need more attention. 

So, are you proposing to use as `Rx.Observable.throwError<string>(Error("Game has no levels defined"))`, ignoring that this observable will never return anything but an error, don't you?

**Comment by motorro** [comment]
Yes. That's the [purpose](http://reactivex.io/documentation/operators/empty-never-throw.html) - nothing but an error. As soon as it emits no value - there is no error. That goes for Observable.empty to. Having them of type <T> gives a way to return them in flatMap (or any other  generator) without explicit type casts and all those warnings.

**Comment by danfma** [comment]
Ok, I will change that!

**Comment by motorro** [comment]
Great! Thank you!

**Comment by danfma** [comment]
I'll try to update the things this weekend. Only one problem, maybe you will have a breaking change... I'm planning to remove the Rx object, so you would use only Observable or Subject directly.

**Comment by motorro** [comment]
No problem for me here. Thanks a lot!

_Sent from my Bq Aquaris M5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by danfma** [comment]
It's on develop branch and on bintray. I still have some changes to do in the directory (like migration for gradle, etc), but you can use it.
